### ISSUE TITLE
Diseño del módulo de atención al usuario

### ISSUE THREAD

**Issue by mimogollon1** [mimogollon1/Tranmiweb#7]
**Con el fin de generar mejor atención al usuario**
Este módulo debe permitir la gestión de incidencias, solicitudes y propuestas de mejora propuestas por los usuarios del aplicativo

-	[x] codificación para registrar una solicitud, propuesta o incidente
-	[x] codificación para que el personal de soporte pueda dar respuestas
-	[x] codificación para que el usuario pueda ser notificado del estado de la solicitud (vía mail, texto al móvil, etc.)

**Comment by yegonzalez23** [comment]
Se valida y esta repetida
